language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit


# removing notifications so that slack key is not exposed in public repositorys
# notifications:
#   slack:
#     rooms:
#       - 3wa-tn-soir-2018:NCO673mv96q0nRHiTfYMsc8r#mytravis
#   email:
#     - anis.dhouieb@gmail.com
